apiVersion: v1
kind: Pod
metadata:
  name: fastapi-pod
spec:
  containers:
    - name: fastapi
      image: marcin119a/fastapi-k8s-demo:latest
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: fastapi-storage
          mountPath: /app/data   # katalog w kontenerze
  volumes:
    - name: fastapi-storage
      persistentVolumeClaim:
        claimName: fastapi-pvc

