apiVersion: v1
kind: Pod
metadata:
  name: mlflow-pod-2
  labels:
    app: mlflow
spec:
  containers:
    - name: mlflow
      image: ghcr.io/mlflow/mlflow:v3.4.0
      args: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]
      ports:
        - containerPort: 5000